#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Authors:
#Cedric H. David, Alan D. Snow, and Luke A. Winslow, 2015-2020.


#*******************************************************************************
#System specifications for Travis CI
#*******************************************************************************
os: linux
language: shell
#This configuration can be validated at: https://config.travis-ci.com/explore


#*******************************************************************************
#Environment variables for different tests on multiple Travis CI workers 
#*******************************************************************************
env:
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_JHM.sh' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_JHM.sh 1 15'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_JHM.sh' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_JHM.sh 16 23'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim1' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 1'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim2' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 2'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim3' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 3'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim4' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 4'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim5' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 5'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim6' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 6'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim7' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 7'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim8' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 8'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim9' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 9'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh sim10' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 10'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh opt' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 11 16'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh opt' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 17 22'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh opt' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 23 82'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_HP.sh opt' TST_PUB_REPR='./tst_pub_repr_David_etal_2011_HP.sh 83 115'
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_2011_JHM.sh' TST_PUB_REPR='./tst_pub_xtra_David_etal_2011_JHM.sh'


#*******************************************************************************
#Before installing RAPID
#*******************************************************************************
before_install:

#-------------------------------------------------------------------------------
#Install operating system dependencies
#-------------------------------------------------------------------------------
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends $(grep -v -E '(^#|^$)' requirements.apt)

#-------------------------------------------------------------------------------
#General environment details
#-------------------------------------------------------------------------------
- apt-get --version
- apt list --installed
- dpkg -l | grep "llvm" | awk '{print $2}'
- find /usr/ -name "*dsymutil*"
- ls -l `find /usr/ -name "*dsymutil*"`
- sudo apt-get autoremove -y llvm*
- sudo rm /usr/local/clang-7.0.0/bin/dsymutil
- dpkg -l | grep "llvm" | awk '{print $2}'
- find /usr/ -name "*dsymutil*"

#-------------------------------------------------------------------------------
#Creating directory for installation of libraries used by RAPID
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- mkdir ../installz
- cd ../installz
- export INSTALLZ_DIR=$PWD

#-------------------------------------------------------------------------------
#Install prerequisites for RAPID
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- ./rapid_install_prereqs.sh -i=$INSTALLZ_DIR

#-------------------------------------------------------------------------------
#Exporting environment variables and adding library-related executables to $PATH
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- source ./rapid_specify_varpath.sh $INSTALLZ_DIR


#*******************************************************************************
#Installing RAPID
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- cd ./src/
- make rapid


#*******************************************************************************
#Testing RAPID 
#*******************************************************************************
script:
- cd $TRAVIS_BUILD_DIR
- cd ./tst/
- gfortran -o tst_run_comp tst_run_comp.f90 -I $TACC_NETCDF_INC -L $TACC_NETCDF_LIB -lnetcdff
- gfortran -o tst_run_cerr tst_run_cerr.f90 -I $TACC_NETCDF_INC -L $TACC_NETCDF_LIB -lnetcdff
- gfortran -o tst_run_conv_Qinit tst_run_conv_Qinit.f90 -I $TACC_NETCDF_INC -L $TACC_NETCDF_LIB -lnetcdff
- echo $TST_PUB_DWNL && $TST_PUB_DWNL
- echo $TST_PUB_REPR && $TST_PUB_REPR
